config/routes.rb
Rails.application.routes.draw do
 
  root 'house_shows#index'
  get 'house_shows', to: 'house_shows#index'

end

app/models/house_show.rb
class HouseShow < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/house_shows_controller.rb
class HouseShowsController < ApplicationController
    def index
        @house_shows = HouseShow.all 
        if params[:sort].present?
            if params[:sort] == "Rating"
                @house_shows = @house_shows.sort_by { |show| show.rating }.reverse!
            elsif params[:sort] == "Release date"
                @house_shows = @house_shows.sort_by { |show| show.release_date }.reverse!
            end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/house_shows_helper.rb
module HouseShowsHelper
end

app/views/house_shows/index.html.erb
<%= render "shared/header"%>
<div class="wrapper-content">
    <div class="sort">
        <%= render "shared/sorting"%>   
    </div>
    <div class="show-list">
        <% @house_shows.each do |show| %>
            <%= render "shared/show_card", show: show%>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<div class="header">
    <p>TOP 3 "HOUSE" TITLED TV-SHOWS</p>
</div>

app/views/shared/_show_card.html.erb
<div class="card">    
    <%=image_tag(show.photo, class: "card-image") %>
    <p class="card-title"><%=show.name%></p>
    <p class="card-rating">Rating: <%=show.rating%></p>
    <p class="card-date">Premiered: <%=show.release_date%></p>
    <p class="card-description">Premiered: <%=show.description%></p>
</div>

app/views/shared/_sorting.html.erb
<%= form_tag house_shows_path, method: :get do %>
    <div class="sort-input">
        <%= select_tag "sort", options_for_select([ "Rating", "Release date" ], params[:sort]),  include_blank: false %>
        <%= submit_tag "Sort"%>
    </div >
<% end %>